### ISSUE TITLE
Where are electron-components and eth-components ?

### ISSUE THREAD

**Issue by paulvi** [ObsidianLabs/Black-IDE#6]
Where are electron-components and eth-components 
that are referenced in package.json ?
```
  "workspaces": [
    "../electron-components/packages/*",
    "../eth-components/packages/*"
  ],
```

**Comment by qftgtr** [comment]
You can find them [here](https://github.com/ObsidianLabs/electron-components) and [here](https://github.com/ObsidianLabs/eth-components). You need to clone them as well and put them in parallel with this repo (make sure to run `yarn` and `yarn build`) if you want to run the IDE from source.

**Comment by paulvi** [comment]
Thanks, it looks like there is no README section about build to add this links...
